# TO USE WITH DOCKER (NEED 1.6 AT LEAST): docker build -t deadcyclo/craftatar-dev -f Dockerfile.dev .
# TODO: Usage, and put in readme

FROM node:5
MAINTAINER Brendan Johan Lee <deadcyclo@vanntett.net>

# Update apt
RUN apt-get update && apt-get -y upgrade

# Install dependencies
RUN apt-get install -y git python-pip libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ nginx redis-server
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN npm install -g forever

# Add the default config file
#ADD config.example.js /app/config.js

# Set up environment
ENV BIND 0.0.0.0
ENV PORT 5000

EXPOSE 5000

